### ISSUE TITLE
Missing type definitions for Input field methods and Tab component not exported

### ISSUE THREAD

**Issue by rebzden-baracoda** [rdkcentral/Lightning-UI-Components#176]
### Description
Firstly, I'd like to express my appreciation for the effort put into this package. It has been a significant help in creating lightning UI.

However, I have encountered some inconsistencies during implementation:

1. The Input field is missing type definitions for the insert(x: string) and backspace() methods. These methods are functional but not defined in the type spec of the input.
2. The documentation includes information about setting the value directly using input.value = "newvalue", but this does not work, regardless of the listening setting.
3. The Tab component does not appear to be exported from the package. I am only able to find the TabBar component.

Thank you again for the great work, and I look forward to your response. Have a wonderful day!

**Comment by erautenberg** [comment]
HI @rebzden-baracoda! I'm so glad to hear that you are enjoying the updates to the project. Thank you for reaching out!

All of these issues seem like pretty easy fixes 🤞 Our team has been utilizing Jira on the internal Comcast side and is hoping to start migrating to GitHub Projects so that our work can be tracked publicly. We're still in the early migration phases, so I won't be able to share a ticket number with you, but we will work on prioritizing these bugs for next week and will share updates with you as soon as possible!

**Comment by erautenberg** [comment]
@rebzden-baracoda all of these issues should be resolved in the latest version!
https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/%40lightningjs%2Fui-components-v2.2.0

Let us know if you observe anything else!

**Comment by rebzden-baracoda** [comment]
Looking great! Thank you 🥰
